name: Request repository creation
description: Create a repository
title: "Request repository creation"
body:
  - type: "input"
    attributes:
      label: "Repository name
      description: "Requested repository name"
      placeholder: "my-new-repo"
    validations:
      required: true
